project:
  type: website
  resources:
    - CNAME

execute:
  freeze: auto

format:
  html:
    # theme: 
    #   light: flatly
    #   dark: darkly
    css: styles.css

website:
  title: "UCL Health Algorithms Laboratory"
  favicon: img/noun-patient-3907718.png
  page-footer: "Copyright 2022 &copy; Steve Harris"
  site-url: https://uclhal.org
  repo-url: https://github.com/uclhal/uclhal
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "News"
        file: news.qmd
      - text: "People"
        file: people.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Tutorials"
        file: tutorials.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - tutorials.qmd
        - tutorials/onboarding/onboarding.qmd
        - tutorials/five-safes/five-safes.qmd
        - tutorials/emap/emap-star-intro.qmd

    - title: "Resources"
      contents:
        - resources.qmd
        - resources/homegrown.qmd
        - resources/awesome.qmd
        # navigation items
    

