project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "AffCom Lab"
  navbar:
    right:
      - href: news.qmd
        text: News
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2022 &copy; Jeffrey Girard"
  google-analytics: "G-K5TXS64QLN"
  site-url: https://affcom.ku.edu
  repo-url: https://github.com/jmgirard/affcomlab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
