project:
  type: website
  resources:
    - CNAME

execute:
  freeze: auto

format:
  html:
    # theme: 
    #   light: flatly
    #   dark: darkly
    css: styles.css
    toc: true

website:
  title: "UCL Health Algorithms Laboratory"
  favicon: img/noun-patient-3907718.png
  page-footer: "Copyright 2022 &copy; Steve Harris"
  site-url: https://uclhal.org
  repo-url: https://github.com/uclhal/uclhal
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "News"
        file: news.qmd
      - text: "People"
        file: people.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Tutorials"
        file: tutorials.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - tutorials.qmd
        - section: "Onboarding"
          contents:
            - tutorials/onboarding/onboarding.qmd
            - tutorials/onboarding/onboarding-1.qmd
            - tutorials/onboarding/onboarding-2.qmd
            - tutorials/five-safes/five-safes.qmd
            - tutorials/emap/emap-star-intro.qmd
        - section: "HYLODE"
          contents:
            - tutorials/hylode/hylode.qmd
            - tutorials/hylode/HyMind-Lab-example.ipynb
            - tutorials/hylode/HyMind-ML-example.ipynb
            - tutorials/hylode/HyCastle-Lens.ipynb
            - tutorials/hylode/vignette_0__README.ipynb
            - tutorials/hylode/vignette_0_intro.ipynb
            - tutorials/hylode/vignette_1_training.ipynb
            - tutorials/hylode/vignette_2_modelling.ipynb
            - tutorials/hylode/vignette_3_data_flow.ipynb

    - title: "Resources"
      contents:
        - resources.qmd
        - resources/homegrown.qmd
        - resources/awesome.qmd
        # navigation items
    

