project:
  type: website
  resources:
    - CNAME
  output-dir: docs

execute:
  freeze: auto

website:
  title: "UCL Health Algorithms Laboratory"
  favicon: img/noun-patient-3907718.png
  navbar:
    pinned: true
    right:
      - href: people.qmd
        text: People
      - href: news.qmd
        text: News
      - text: Research
        menu:
          - href: featured.qmd
            text: Featured
          - href: publications.qmd
            text: Publications
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2022 &copy; Steve Harris"
  site-url: https://uclhal.org
  repo-url: https://github.com/uclhal/uclhal
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
