project:
  type: website
  resources:
    - CNAME
  output-dir: docs

execute:
  freeze: auto

website:
  title: "UCL Health Algorithms Laboratory"
  navbar:
    pinned: true
    right:
      - href: people.qmd
        text: People
      - href: news.qmd
        text: News
      # - href: research.qmd
      #   text: Research
      - text: Research
        menu:
          - href: featured.qmd
            text: Featured
          - href: publications.qmd
            text: Publications
      - href: resources.qmd
        text: Resources
      # - href: opportunities.qmd
      #   text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2022 &copy; Steve Harris"
  site-url: https://uclhal.org
  repo-url: https://github.com/uclhal/uclhal

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
