- cite_key: arulkumaranUncontrolledInterventionsPandemics2020a
  authors: Arulkumaran N, Wright T, Harris S, Singer M
  title: 'Uncontrolled interventions during pandemics: a missed learning opportunity?'
  journal: Intensive Care Medicine
  year: 2020
  doi: 10.1007/s00134-020-06180-6
  url: https://link.springer.com/10.1007/s00134-020-06180-6
  url4title: http://doi.org/10.1007/s00134-020-06180-6
- cite_key: banerjeeEstimatingExcess1year2020a
  authors: Banerjee A, Pasea L, Harris S, Gonzalez-Izquierdo A, Torralbo A, Shallcross
    L, Noursadeghi M, Pillay D, Sebire N, Holmes C, Pagel C, Wong W, Langenberg C,
    Williams B, Denaxas S, Hemingway H
  title: 'Estimating excess 1-year mortality associated with the COVID-19 pandemic
    according to underlying conditions and age: a population-based cohort study'
  journal: The Lancet
  year: 2020
  doi: 10.1016/S0140-6736(20)30854-0
  url: https://linkinghub.elsevier.com/retrieve/pii/S0140673620308540
  url4title: http://doi.org/10.1016/S0140-6736(20)30854-0
- cite_key: chenNudgingLearningHealth2022b
  authors: Chen Y, Harris S, Rogers Y, Ahmad T, Asselbergs F
  title: 'Nudging within learning health systems: next generation decision support
    to improve cardiovascular care'
  journal: European Heart Journal
  year: 2022
  doi: 10.1093/eurheartj/ehac030
  url: https://academic.oup.com/eurheartj/article/43/13/1296/6525340
  url4title: http://doi.org/10.1093/eurheartj/ehac030
- cite_key: critcareasiaEstablishingCriticalCare2020a
  authors: ' , Beane A, Dondorp A, Taqi A, Ahsan A, Vijayaraghavan B, Permpikul C,
    Pell C, Gandy D, Priyadarshani D, Aryal D, Khiem D, Thuy D, Thwaites G, Kayastha
    G, Udayanga I, Salluh J, Detleuxay K, Ranganathan L, Yen L, Har L, Thwaites L,
    Hashmi M, Schultz M, Mukaka M, Leaver M, Nor M, Hayat M, Day N, Moonesinghe R,
    Haniffa R, Champunot R, Inglis R, Sultana R, Yacoub S, Harris S, Acharya S, Tripathy
    S, Ali S, Kadhiravan T, Lubell Y'
  title: Establishing a critical care network in Asia to improve care for critically
    ill patients in low- and middle-income countries
  journal: Critical Care
  year: 2020
  doi: 10.1186/s13054-020-03321-7
  url: https://ccforum.biomedcentral.com/articles/10.1186/s13054-020-03321-7
  url4title: http://doi.org/10.1186/s13054-020-03321-7
- cite_key: domiziRelationshipNorepinephrineDose2020a
  authors: Domizi R, Calcinaro S, Harris S, Beilstein C, Boerma C, Chiche J, D'Egidio
    A, Damiani E, Donati A, Koetsier P, Madden M, McAuley D, Morelli A, Pelaia P,
    Royer P, Shankar-Hari M, Wickboldt N, Zolfaghari P, Singer M
  title: 'Relationship between norepinephrine dose, tachycardia and outcome in septic
    shock: A multicentre evaluation'
  journal: Journal of Critical Care
  year: 2020
  doi: 10.1016/j.jcrc.2020.02.014
  url: https://linkinghub.elsevier.com/retrieve/pii/S0883944119313590
  url4title: http://doi.org/10.1016/j.jcrc.2020.02.014
- cite_key: flowerAcuteSTsegmentElevation2021a
  authors: Flower L, Bares Z, Santiapillai G, Harris S
  title: Acute ST-segment elevation myocardial infarction secondary to vaccine-induced
    immune thrombosis with thrombocytopaenia (VITT)
  journal: BMJ Case Reports CP
  year: 2021
  doi: 10.1136/bcr-2021-245218
  url: https://casereports.bmj.com/content/14/9/e245218
  url4title: http://doi.org/10.1136/bcr-2021-245218
- cite_key: ghorashianTisagenlecleucelTherapyRelapsed2022a
  authors: Ghorashian S, Jacoby E, De Moerloose B, Rives S, Bonney D, Shenton G, Bader
    P, Bodmer N, Quintana A, Herrero B, Algeri M, Locatelli F, Vettenranta K, Gonzalez
    B, Attarbaschi A, Harris S, Bourquin J, Baruchel A
  title: 'Tisagenlecleucel therapy for relapsed or refractory B-cell acute lymphoblastic
    leukaemia in infants and children younger than 3 years of age at screening: an
    international, multicentre, retrospective cohort study'
  journal: The Lancet Haematology
  year: 2022
  doi: 10.1016/S2352-3026(22)00225-3
  url: https://www.sciencedirect.com/science/article/pii/S2352302622002253
  url4title: http://doi.org/10.1016/S2352-3026(22)00225-3
- cite_key: harrisClinicalDeploymentEnvironments2022
  authors: Harris S, Bonnici T, Keen T, Lilaonitkul W, White M, Swanepoel N
  title: 'Clinical deployment environments: Five pillars of translational machine
    learning for health'
  journal: Frontiers in Digital Health
  year: 2022
  doi: 10.3389/fdgth.2022.939292
  url: https://www.frontiersin.org/articles/10.3389/fdgth.2022.939292
  url4title: http://doi.org/10.3389/fdgth.2022.939292
- cite_key: harrisDonWantMy2021a
  authors: Harris S
  title: 'I Don''t Want My Algorithm to Die in a Paper: Detecting Deteriorating Patients
    Early'
  journal: American Journal of Respiratory and Critical Care Medicine
  year: 2021
  doi: 10.1164/rccm.202102-0459ED
  url: https://www.atsjournals.org/doi/10.1164/rccm.202102-0459ED
  url4title: http://doi.org/10.1164/rccm.202102-0459ED
- cite_key: harrisTrialsPandemicsHere2021a
  authors: Harris S, Palmer E, Fong K
  title: 'Trials in pandemics: here we go again?'
  journal: British Journal of Anaesthesia
  year: 2021
  doi: 10.1016/j.bja.2020.10.008
  url: https://linkinghub.elsevier.com/retrieve/pii/S0007091220308400
  url4title: http://doi.org/10.1016/j.bja.2020.10.008
- cite_key: hashimPerceptionsUKClinicians2021a
  authors: Hashim S, Wong D, Farmer L, Harris S, Moonesinghe S
  title: Perceptions of UK clinicians towards postoperative critical care
  journal: Anaesthesia
  year: 2021
  doi: 10.1111/anae.15302
  url: https://onlinelibrary.wiley.com/doi/10.1111/anae.15302
  url4title: http://doi.org/10.1111/anae.15302
- cite_key: keeleStrongerInstrumentsRefined2020a
  authors: Keele L, Harris S, Pimentel S, Grieve R
  title: Stronger instruments and refined covariate balance in an observational study
    of the effectiveness of prompt admission to intensive care units
  journal: 'Journal of the Royal Statistical Society: Series A (Statistics in Society)'
  year: 2020
  doi: 10.1111/rssa.12437
  url: https://onlinelibrary.wiley.com/doi/10.1111/rssa.12437
  url4title: http://doi.org/10.1111/rssa.12437
- cite_key: kingMachineLearningRealtime2022a
  authors: King Z, Farrington J, Utley M, Kung E, Elkhodair S, Harris S, Sekula R,
    Gillham J, Li K, Crowe S
  title: Machine learning for real-time aggregated prediction of hospital admission
    for emergency patients
  journal: npj Digital Medicine
  year: 2022
  doi: 10.1038/s41746-022-00649-y
  url: https://doi.org/10.1038/s41746-022-00649-y
  url4title: http://doi.org/10.1038/s41746-022-00649-y
- cite_key: krishnamoorthyCausalInferencePerioperative2020b
  authors: Krishnamoorthy V, Wong D, Wilson M, Raghunathan K, Ohnuma T, McLean D,
    Moonesinghe S, Harris S
  title: 'Causal inference in perioperative medicine observational research: part
    1, a graphical introduction'
  journal: British Journal of Anaesthesia
  year: 2020
  doi: 10.1016/j.bja.2020.03.031
  url: https://linkinghub.elsevier.com/retrieve/pii/S0007091220302932
  url4title: http://doi.org/10.1016/j.bja.2020.03.031
- cite_key: krishnamoorthyCausalInferencePerioperative2020c
  authors: Krishnamoorthy V, McLean D, Ohnuma T, Harris S, Wong D, Wilson M, Moonesinghe
    R, Raghunathan K
  title: 'Causal inference in perioperative medicine observational research: part
    2, advanced methods'
  journal: British Journal of Anaesthesia
  year: 2020
  doi: 10.1016/j.bja.2020.03.032
  url: https://linkinghub.elsevier.com/retrieve/pii/S0007091220303020
  url4title: http://doi.org/10.1016/j.bja.2020.03.032
- cite_key: laiInformaticsConsultApproach2021a
  authors: Lai A, Chang W, Parisinos C, Katsoulis M, Blackburn R, Shah A, Nguyen V,
    Denaxas S, Davey Smith G, Gaunt T, Nirantharakumar K, Cox M, Forde D, Asselbergs
    F, Harris S, Richardson S, Sofat R, Dobson R, Hingorani A, Patel R, Sterne J,
    Banerjee A, Denniston A, Ball S, Sebire N, Shah N, Foster G, Williams B, Hemingway
    H
  title: An informatics consult approach for generating clinical evidence for treatment
    decisions
  journal: BMC Medical Informatics and Decision Making
  year: 2021
  doi: 10.1186/s12911-021-01638-z
  url: https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-021-01638-z
  url4title: http://doi.org/10.1186/s12911-021-01638-z
- cite_key: newcombeFutureAcuteEmergency2021a
  authors: Newcombe V, Coats T, Dark P, Gordon A, Harris S, McAuley D, Menon D, Price
    S, Puthucheary Z, Singer M
  title: The future of acute and emergency care
  journal: Future Healthcare Journal
  year: 2021
  doi: 10.7861/fhj.2021-0097
  url: https://www.rcpjournals.org/lookup/doi/10.7861/fhj.2021-0097
  url4title: http://doi.org/10.7861/fhj.2021-0097
- cite_key: postOxygenationCriticallyIll2020a
  authors: Post B, Palmer E, Harris S, Singer M, Martin D
  title: 'Oxygenation of the critically ill in selected intensive care units in the
    UK: are we usual?'
  journal: British Journal of Anaesthesia
  year: 2020
  doi: 10.1016/j.bja.2020.06.033
  url: https://linkinghub.elsevier.com/retrieve/pii/S0007091220304931
  url4title: http://doi.org/10.1016/j.bja.2020.06.033
- cite_key: shahDescriptorsSepsisUsing2021a
  authors: Shah A, MacCallum N, Harris S, Brealey D, Palmer E, Hetherington J, Shi
    S, Perez-Suarez D, Ercole A, Watkinson P, Jones A, Ashworth S, Beale R, Brett
    S, Singer M
  title: 'Descriptors of Sepsis Using the Sepsis-3 Criteria: A Cohort Study in Critical
    Care Units Within the U.K. National Institute for Health Research Critical Care
    Health Informatics Collaborative*'
  journal: Critical Care Medicine
  year: 2021
  doi: 10.1097/CCM.0000000000005169
  url: https://journals.lww.com/10.1097/CCM.0000000000005169
  url4title: http://doi.org/10.1097/CCM.0000000000005169
- cite_key: tissotNaturalLanguageProcessing2020a
  authors: Tissot H, Shah A, Brealey D, Harris S, Agbakoba R, Folarin A, Romao L,
    Roguski L, Dobson R, Asselbergs F
  title: 'Natural Language Processing for Mimicking Clinical Trial Recruitment in
    Critical Care: A Semi-Automated Simulation Based on the LeoPARDS Trial'
  journal: IEEE Journal of Biomedical and Health Informatics
  year: 2020
  doi: 10.1109/JBHI.2020.2977925
  url: https://ieeexplore.ieee.org/document/9027845/
  url4title: http://doi.org/10.1109/JBHI.2020.2977925
- cite_key: wilsonClinicianPreferenceInstrumental2022a
  authors: Wilson M, Rashan A, Klapaukh R, Asselbergs F, Harris S
  title: Clinician preference instrumental variable analysis of the effectiveness
    of magnesium supplementation for atrial fibrillation prophylaxis in critical care
  journal: Scientific Reports
  year: 2022
  doi: 10.1038/s41598-022-21286-1
  url: https://www.nature.com/articles/s41598-022-21286-1
  url4title: http://doi.org/10.1038/s41598-022-21286-1
- cite_key: wilsonEmbeddedPointCare2022a
  authors: Wilson M, Asselbergs F, Miguel R, Brealey D, Harris S
  title: 'Embedded point of care randomisation for evaluating comparative effectiveness
    questions: PROSPECTOR-critical care feasibility study protocol'
  journal: BMJ Open
  year: 2022
  doi: 10.1136/bmjopen-2021-059995
  url: https://bmjopen.bmj.com/lookup/doi/10.1136/bmjopen-2021-059995
  url4title: http://doi.org/10.1136/bmjopen-2021-059995
- cite_key: wilsonLearningIndividualisedVariation2022a
  authors: Wilson M, Asselbergs F, Harris S
  title: Learning from individualised variation for evidence generation within a learning
    health system
  journal: British Journal of Anaesthesia
  year: 2022
  doi: 10.1016/j.bja.2022.02.008
  url: https://linkinghub.elsevier.com/retrieve/pii/S0007091222000757
  url4title: http://doi.org/10.1016/j.bja.2022.02.008
- cite_key: wongDevelopingValidatingSubjective2020a
  authors: Wong D, Harris S, Sahni A, Bedford J, Cortes L, Shawyer R, Wilson A, Lindsay
    H, Campbell D, Popham S, Barneto L, Myles P,  , Moonesinghe S
  title: 'Developing and validating subjective and objective risk-assessment measures
    for predicting mortality after major surgery: An international prospective cohort
    study'
  journal: PLOS Medicine
  year: 2020
  doi: 10.1371/journal.pmed.1003253
  url: https://dx.plos.org/10.1371/journal.pmed.1003253
  url4title: http://doi.org/10.1371/journal.pmed.1003253
