name: Render pull request

on: 
  pull_request

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy PR Preview
        uses: dan-hanlon/pr-preview-action@62f1f6206ef1e71283c58ced9a978c429e6140ec
        with:
          source-dir: ./_site/
          custom-url: uclhal.org
